clone_depth: 1

platform: x86

before_build:
- git clone https://github.com/vjrantal/DeveloperLicenseAcquirer.git
- msbuild DeveloperLicenseAcquirer\DeveloperLicenseAcquirer.sln /p:"platform"="Any CPU" /verbosity:minimal
- DeveloperLicenseAcquirer\DeveloperLicenseAcquirer\bin\Debug\DeveloperLicenseAcquirer.exe "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\TailoredDeploy.exe" %username% %pwd%
- nuget restore ReactWindows\ReactNative.sln

build:
  project: ReactWindows\ReactNative.sln
  verbosity: minimal

test_script:
- ps: Import-Certificate -CertStoreLocation cert:\LocalMachine\CA -FilePath .\ReactWindows\ReactNative.Tests\AppPackages\ReactNative.Tests_1.0.0.0_x86_Debug_Test\ReactNative.Tests_1.0.0.0_x86_Debug.cer
- dir ReactWindows\ReactNative.Tests\AppPackages\ReactNative.Tests_1.0.0.0_x86_Debug_Test
- vstest.console ReactWindows\ReactNative.Tests\AppPackages\ReactNative.Tests_1.0.0.0_x86_Debug_Test\ReactNative.Tests_1.0.0.0_x86_Debug.appx
